In [1]:
print(2+3)

5


In [2]:
print("Привет", input())

Артём
Привет Артём


In [3]:
!pip install numpy


In [10]:
import numpy as np
arr = np.array([[1,2,4], [1,2,3]])
arr1 = np.array([[5,6,7], [5,6,7]])

In [12]:
print(arr*5)

[[ 5 10 20]
 [ 5 10 15]]


In [15]:
import numpy as np
def cumulative_mean(X):
    result = np.cumsum(X)
    new_arr = np.array(1,len(X) + 1)
    result = result / new_arr
    return result

In [23]:
import numpy as np
def cumulative_mean(X):
    result = np.cumsum(X)
    new_arr = np.arange(1,len(X) + 1)

    result = result / new_arr
    return result
# test
a = np.array([1, 2, 4, -9])
print(cumulative_mean(a))

assert np.allclose(cumulative_mean(a), np.array([1, 1.5, 7./3, -0.5]))

[ 1.          1.5         2.33333333 -0.5       ]


In [41]:
import numpy as np
def cumulative_mean_2d(A):
    result = np.cumsum(A).reshape(2, len(A[0]))
    new_arr = np.arange(1,len(A[0]) * 2 + 1).reshape(2, len(A[0]))
    print(result, new_arr)
    result = result / new_arr
    return result

#test
a = np.array([1, 2, 4, -9, 1, 1, 1, 1]).reshape(2, 4)

print(cumulative_mean_2d(np.array([[1, 2, 3],[4, 5, 6]])))

[[ 1  3  6]
 [10 15 21]] [[1 2 3]
 [4 5 6]]
[[1.  1.5 2. ]
 [2.5 3.  3.5]]


In [49]:
import numpy as np
def cumulative_mean_2d(A):
    result =  np.cumsum(A, axis=1)
    new_arr = np.cumsum(np.ones(A.shape), axis=1)
    result = result / new_arr
    return result
print(cumulative_mean_2d(np.array([[1, 2, 3],[4, 5, 6]])))

[[1.  1.5 2. ]
 [4.  4.5 5. ]]


In [50]:
def diag_2k(a):
    sum = 0
    for i in np.diag(a):
        sum += 0 if i % 2 else i
    return sum

In [51]:
diag_2k([[2, 2, 3], [4, 5, 6], [7, 8, 9]])

2

In [2]:
import numpy as np

def calculate_loss_function(X, w, y):
    return np.square(np.linalg.norm(X @ w - y.T))
X = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([1, 2, 3])
y = np.array([1, 2])
print(calculate_loss_function(X, w, y))

1069.0000000000002
